CHAAAAAAAAAAAOOOOOOOOOSSSSSSS
Chaosthebot/Chaos pull request #101
Opened 2017-05-23 21:29 UTC by EtherTyper

2017-05-23 22:25 UTC, sugar700 approved these changes
Otherwise fine, upvoting just because this will be rejected anyway.

2017-05-23 22:25 UTC, xfix commented on README.md
> +### _CHAAAAAAAAAAAOOOOOOOOOSSSSSSS_
Shouldn't be italics and all-caps

2017-05-23 22:25 UTC, xfix commented on README.md
>  ![Image of a kitten with overlay: "I WONDER IF BEING SANE MEANS DISREGARDING THE CHAOS THAT IS LIFE...PRETENDING ONLY AN INFINITESIMAL SEGMENT OF IT IS REALITY" Source: http://existentialpets.tumblr.
Left kitten alone

2017-05-23 22:25 UTC, xfix commented on README.md
> -## How it works
How are people going to know how to use the bot if there are no instructions.

2017-05-23 22:25 UTC, xfix commented on README.md
> +### _CHAAAAAAAAAAAOOOOOOOOOSSSSSSS_
Or you know, should be italics and all caps twice. Like, twice as upper case characters.

2017-05-23 22:25 UTC, xfix commented on README.md
> -## Server details
How are users going to know server parameters

2017-05-24 07:35 UTC, rvegas commented
👎

2017-05-25 03:13 UTC, eamanu commented
(N)

2017-05-25 11:48 UTC, Shuunen commented
👎

2017-05-25 12:12 UTC, jblz requested changes
mean <> chaotic :-1:

2017-05-26 04:15 UTC, ozyx commented
Why hasn't this been closed yet? :|

2017-05-26 04:28 UTC, reddraggone9 commented
@ozyx 

This can't be merged or closed by votes because there are still conflicts which need to be resolved. It will eventually be closed for being stale. Right now, [that code][0] looks at the [last push to the originating repo][1], which was [10 hours ago][2]. With the current code, it needs [24 hours][3] before it will be closed as stale.

#271 will instead have Chaos look at the last push to *this particular PR* instead.

[0]: https://github.com/chaosbot/Chaos/blob/4a88895b058e9ada04be023443d7d458870f64e9/github_api/prs.py#L150-L155
[1]: https://github.com/chaosbot/Chaos/blob/4a88895b058e9ada04be023443d7d458870f64e9/github_api/prs.py#L104-L112
[2]: https://github.com/EtherTyper/chaos/commit/e44bdb5a14305008e2111e445d8b0a8bd4c80f9c
[3]: https://github.com/chaosbot/Chaos/blob/4a88895b058e9ada04be023443d7d458870f64e9/settings.py#L69-L71

2017-05-26 08:26 UTC, closed without merging