Remove the Rickroll
Chaosthebot/Chaos pull request #202
Opened 2017-05-24 22:00 UTC by xyproto

To quote a [random poem](https://www.familyfriendpoems.com/poem/carry-on) I found online:

> I don't hate you, 
> Because I still love you. 
> I can't look at you, 
> Because it hurts to.
> We don't talk, 
> Because there is nothing left to say.

The Rick Roll has had its golden age. It's time to let it go.

2017-05-24 22:10 UTC, dehodson approved these changes

2017-05-24 22:42 UTC, EtherTyper commented
:-1: Long live Rick Roll, it's golden age is all eternity.

2017-05-25 01:22 UTC, jblz approved these changes

2017-05-25 02:36 UTC, JamesWatling requested changes
I just want to tell you how I'm feeling
Gotta make you understand

You know the rules and so do I

We know the game and we're gonna play it

2017-05-25 10:36 UTC, xyproto commented
Rickroll has been removed by some other pull request.

2017-05-25 10:36 UTC, closed without merging