Solve #237 bug
Chaosthebot/Chaos pull request #239
Opened 2017-05-25 12:34 UTC by eamanu

Solve indent proble in chaos.py

2017-05-25 16:28 UTC, ad-m commented on chaos.py
>                              format='%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
Do you can fix indent of that line too? See #246 for the right solution.

2017-05-26 01:13 UTC, rhengles requested changes
Has a merge conflict

2017-05-26 01:14 UTC, merged

2017-05-26 01:14 UTC, rhengles commented
💩 !

2017-05-26 01:16 UTC, rhengles commented
There was a commit 5 minutes ago, @chaosbot shouldn't have merged this, it should have reset the voting time!

2017-05-26 01:28 UTC, amoffat commented
@rhengles you're right, it looks like there's a bug.  look at the top of the PR where it says `from unknown repo`.  This usually happens when you delete the repo backing a PR.  In order for github to keep the PR valid, the changeset lives somewhere... `unknown repo`.  Now, when @eamanu did the merge conflict fix, I would bet he did it in the browser, which means that that new conflict fix commit also lived at github's magic `unknown repo` as well, with the rest of his changes.  When chaos tries to find out how old a PR is for voting, it looks for the the repo backing a PR, and if it can't find it, [it defaults to](https://github.com/chaosbot/Chaos/blob/master/github_api/prs.py#L104-L112) the PR's creation date.

2017-05-26 01:28 UTC, amoffat commented
i'll address this shortly in a new PR