Get issue comments
Chaosthebot/Chaos pull request #284
Opened 2017-05-26 13:43 UTC by rudehn

Start working towards #192 by retrieving issue comments

2017-05-26 13:50 UTC, hongaar commented
Awesome! Was just about to start working on this, too ;)

2017-05-26 14:28 UTC, hongaar commented
@rudehn like were this is going! Maybe add [WIP] in your title to hold off voting window for now...

2017-05-26 14:41 UTC, rudehn commented
The only issue is this doesn't support getting reactions on the comments. Haven't figured that one out yet

2017-05-26 15:55 UTC, rudehn commented
Ok this could definitely use a review.

2017-05-26 18:11 UTC, PlasmaPower commented
Instead of no -1s, how about a positive total? (when including the author as an implicit +1)

2017-05-26 18:16 UTC, rudehn commented
Sure that's definitely a possibility. This method is just implementing  #192. If the community comes up with a better way, then we will go with that.

2017-05-26 18:18 UTC, hongaar commented
Hmm.. why not? Can't test the code right now, its way too sunny outside, but looking good! One question: how does it track which commands did already pass before? If say a reopen command was passed, and the author closes the issue later on, won't it automatically reopen it again?

2017-05-26 18:20 UTC, PlasmaPower commented
It looks like you're right: a command will be continually reapplied until down voted. That could cause problems.

2017-05-26 18:22 UTC, rudehn commented
Yeah it definitely will haha. This is a first pass for POC with respect to closing issues and getting a general framework in place for submitting commands.

I'll look into saving the previously ran commands into a json file. Would be nice if we had mysql support up..

2017-05-26 18:23 UTC, PlasmaPower commented
We do have MySQL IIRC, just no interface to it.

2017-05-26 18:25 UTC, reddraggone9 commented
You could also have @chaosbot add a reaction to record that it ran/didn't run the command.

2017-05-26 18:28 UTC, rudehn commented
@reddraggone9 that's true. 

I was going to suggest we keep a timestamp that indicates where we stopped at last time we ran commands. We could sort the issue comments by "created_at" date. And wait for them to go through the voting window. Then we only retrieve new issue comments after our previous timestamp we left off at.

This would probably interfere with updating commands and resetting the voting window etc...

A safer solution I think would be to just save the comment id and never run the command from that comment id again.

2017-05-26 19:01 UTC, hongaar commented
@rudehn saving the comment IDs as a means of recording them as 'already processed, ignore from now on' sounds good to me. Would be great if this list could be persisted in the repo itself? (i.e. chaosbot updates a text file and pushes that up to the GH repo?)

2017-05-26 19:27 UTC, amoffat commented
Very cool stuff @rudehn!  If you're using the docker dev env to test your stuff, let me know how that works out for you, so it can be improved

2017-05-26 22:52 UTC, xyproto commented on cron/poll_read_issue_comments.py
> +                if(sub_command == "label"):
A bit shorter:

```python
if sub_command[0] not in ["label", "remove-label", "assign", "unassign"]:
    log_warning = True
```

2017-05-26 23:16 UTC, rudehn commented on cron/poll_read_issue_comments.py
> +                if(sub_command == "label"):
it is, but you still have to check which command you need to run. These commands would be implemented sometime in the future

2017-05-27 07:41 UTC, aslafy-z commented on cron/poll_read_issue_comments.py
> +    if(len(command)):
Please, write pythonic code (remove the parentheses around the ifs) !

2017-05-27 07:47 UTC, xyproto commented on cron/poll_read_issue_comments.py
> +                if(sub_command == "label"):
I think it's better to implement things as they are needed. Scaffolding for the future can easily create unmanagable code bases over time. Someone will have to remember to actually do the implementation sometime in the future, and this does not always happen.

2017-05-27 13:05 UTC, rudehn commented on cron/poll_read_issue_comments.py
> +    if(len(command)):
Ahh my bad!! I totally agree.

2017-05-28 03:28 UTC, rudehn commented
Looking to finish this up soon. Been a busy weekend

2017-05-28 13:46 UTC, rudehn commented
Alright its up! Voting commands for closing and reopening issues is working.

Todo

- [ ] Add chaos response to issue command similar to PR status

2017-05-28 14:02 UTC, phil-r commented
@rudehn Something is wrong with a PR 😕

2017-05-28 14:25 UTC, rudehn commented
Certainly looks like it. I'll see if I can figure out what happened

2017-05-28 14:32 UTC, aslafy-z commented on cron/poll_read_issue_comments.py
> +            if len(sub_command > 1):
Should be `len(sub_command) > 1:` right ?

2017-05-28 14:35 UTC, aslafy-z commented on cron/poll_read_issue_comments.py
> +            if len(sub_command > 1):
Should be `len(sub_command)  > 1:` right ?

2017-05-28 18:06 UTC, phil-r requested changes
@rudehn I'm forced to downvote, until the mess(110 commits and 44 files changed) is fixed 👎

2017-05-28 18:37 UTC, phil-r commented
@rudehn maybe this will help: #339

2017-05-28 18:41 UTC, aslafy-z commented
Please switch back your PR to WIP until it's clean @rudehn

2017-05-28 19:06 UTC, rudehn commented
I'm not sure how to fix it. I don't really know what happened

2017-05-28 19:36 UTC, closed without merging