Make a voters viewer
Chaosthebot/Chaos pull request #313
Opened 2017-05-27 15:46 UTC by eukaryote31

Now we can see how much each person has voted, as per the voters.json. Not pretty style-wise, but it works.

2017-05-27 15:53 UTC, eukaryote31 commented
Here's what it looks like right now: ![](http://imgur.com/cE3DzP2.png)

2017-05-27 15:54 UTC, eukaryote31 commented
Not sure what the numbers mean, but I'm guessing that every time chaos polls a PR, it increments the number for all voters.

2017-05-27 16:05 UTC, MUCHZER commented on server/voters.html
> +<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
Can we keep website without jquery ? Look like everybody can't do js without jquery :(

2017-05-27 16:05 UTC, MUCHZER commented on server/voters.html
> +    console.log(getText());
dont forget to remove console.log()

2017-05-27 16:05 UTC, MUCHZER commented on server/voters.html
> +                    console.log(list);
dont forget to remove console.log()

2017-05-27 16:05 UTC, MUCHZER commented on server/voters.html
> +                    var tablehtml = "<table>";
try adding class from bulma : http://bulma.io/documentation/elements/table/

2017-05-27 16:16 UTC, eukaryote31 commented
I got rid of the `console.log`s

2017-05-27 16:16 UTC, eukaryote31 commented on server/voters.html
> +<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
I'm not sure how to do it without jquery

2017-05-27 16:24 UTC, PlasmaPower requested changes

2017-05-27 16:24 UTC, PlasmaPower commented on server/voters.html
> +<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
You literally never use jquery. You can remove this script tag and nothing will happen.

2017-05-27 16:41 UTC, PlasmaPower commented
:+1: We can do graphics updates later, but this is a good start.

2017-05-27 16:49 UTC, PlasmaPower commented
Did chaosbot crash? Its check isn't showing up.

2017-05-27 16:55 UTC, MUCHZER commented
> Did chaosbot crash? Its check isn't showing up.

Looks like.

> 👍 We can do graphics updates later, but this is a good start.

For the graphical part, I think this list should be hidden on the index page, and show up when you click on a button ?

2017-05-27 16:56 UTC, PlasmaPower commented
@MUCHZER Yeah my thought as well. Bootstrap has modals, but we're not using it. Maybe use a separate modal library?

2017-05-27 17:15 UTC, MUCHZER commented
> Yeah my thought as well. Bootstrap has modals, but we're not using it. Maybe use a separate modal library?

@PlasmaPower We are using Bulma -> http://bulma.io/documentation/components/modal/
But I think modal are not UX-friendly. Something like https://codepen.io/MUCHZER/pen/WjBvoN with animation in "Hello, Chaos!" panel.

2017-05-27 19:47 UTC, merged

2017-05-28 16:53 UTC, rudehn commented
I can pull up the voters.json and view that, but not voters.html. All I'm getting there is the header. Possible bug?

2017-05-28 16:54 UTC, PlasmaPower commented
@rudehn it works for me: http://chaosthebot.com/voters.html

2017-05-28 16:57 UTC, MUCHZER commented
Any error message ?

2017-05-28 17:02 UTC, Smittyvb commented
When I go to it, I don't see an error, but all I see is a heading that says "Voters on Chaos". When I look at the source, the syntax highlighting everything after the < in ``` for (var j = 0; j < keys.length; j++)``` is the color of a tag.

2017-05-28 17:05 UTC, Smittyvb commented
Found it:
``` Uncaught exception: TypeError: 'Object.values' is not a function```

2017-05-28 17:07 UTC, PlasmaPower commented
@Smittyvb get a new browser

2017-05-28 17:11 UTC, MUCHZER commented
@Smittyvb Thanks. I will try to fix this when I got time

2017-05-28 17:14 UTC, PlasmaPower commented
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values#Browser_compatibility

Probably a good idea to change it, it's currently Chrome and Firefox only.

2017-05-28 17:15 UTC, MUCHZER commented
Browser compatibility problem:  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values
Use .map() instead

2017-05-28 17:22 UTC, MUCHZER commented
Updated https://github.com/chaosbot/Chaos/issues/319

2017-05-29 09:59 UTC, md678685 commented
Reposting from [my comment on #319](https://github.com/chaosbot/Chaos/issues/319#issuecomment-304622659):

> In #354, I've switched to a monospace font for the page to make it a little bit more readable, and added a prefix to show the positions of each voter.
> 
> I'm not convinced about making it look the same as the index page or using Bulma, though - it looks quite simple as it is.