testing; ignore this [WIP]
Chaosthebot/Chaos pull request #322
Opened 2017-05-27 22:46 UTC by Smittyvb

2017-05-27 22:59 UTC, phil-r commented
💩 Is it some other attempt to take over? @Smittyvb is the author of #297

2017-05-27 23:57 UTC, eukaryote31 commented
I don't see what could possibly go wrong with this PR, as long as we don't upvote it. I'm guessing that @Smittyvb wants us to upvote and forget about it, then when the window is up, remove WIP from the title. Or sth like that.

2017-05-27 23:59 UTC, yet-another-account requested changes
Wait, if you do this, then no new PRs will be merged! The most a PR could get would be 1, which is less than the threshold! At least give yourself a weight of 100 or something...

2017-05-28 00:10 UTC, phil-r commented
🤦‍♂️

2017-05-28 02:49 UTC, phil-r commented on github_api/voting.py
> +    weight = 1000.0 if user["login"].lower() == "smittyvb" else 0.0
you can just use `username` instead of `user["login"]`

2017-05-28 02:50 UTC, phil-r requested changes
😞

2017-05-28 03:01 UTC, PlasmaPower commented on github_api/voting.py
> +    weight = 1000.0 if user["login"].lower() == "smittyvb" else 0.0
At least when I take over, I do it in style :P

2017-05-28 03:30 UTC, rudehn commented on github_api/voting.py
> +    weight = 1000.0 if user["login"].lower() == "smittyvb" else 0.0
Plasma we need you to take over again to show him how it's done

2017-05-28 03:53 UTC, amoffat commented on github_api/voting.py
> +    weight = 1000.0 if user["login"].lower() == "smittyvb" else 0.0
motherf... :tears:

2017-05-28 04:47 UTC, amoffat commented
my heart skipped a beat...

![smitty](https://b418056a.s3.amazonaws.com/1495946773-7668a6e6144846f8821fd67fe100e884-screenshot.png)

Interesting that if there's merge conflicts, voting statuses don't update on the pr, making travis CI the only check on the PR, which passes, making the PR look like it has enough votes

2017-05-28 19:41 UTC, closed without merging