Start getting an interface for MySQL
Chaosthebot/Chaos pull request #381
Opened 2017-05-30 01:12 UTC by rudehn

Just starting to flesh out some code

2017-05-30 01:37 UTC, PlasmaPower commented
Mark as WIP? or do you think it's done enough to merge as a base?

2017-05-30 09:15 UTC, hongaar commented
Would sqlite be an option? Waaay less overhead and waaay more better unless we're going to build the next social network...?

2017-05-30 10:59 UTC, rudehn commented
I would prefer it, but mysql was already present in the Dockerfile. I'm not sure if it's being used anywhere in production though.

2017-05-31 10:38 UTC, syvb approved these changes

2017-05-31 10:40 UTC, syvb approved these changes

2017-06-01 05:17 UTC, andrewda requested changes
Looks good, just one tiny change

2017-06-01 05:17 UTC, andrewda commented on db/db.py
> +
Remove extra new line (example from elsewhere in the code: https://github.com/chaosbot/Chaos/blob/9dabaf3349f64c9b7a4b9d32e3a1ccb7afa8122e/cron/poll_issue_close_stale.py#L7)

2017-06-01 12:38 UTC, rudehn commented
See #456

2017-06-01 12:38 UTC, closed without merging

2017-06-01 13:29 UTC, hongaar commented
Let's keep it though, who knows we'll be building the next social network anyway: #461