[WIP] Bring back mandatory travis-ci check
Chaosthebot/Chaos pull request #412
Opened 2017-05-30 23:16 UTC by phil-r

- [x] It doesn't block PRs if status is not added for some reason
- [ ] Decide if we need a new label (`ci failed` for example) and whether we should close PRs that can't pass CI for a long time (as we do with PRs with conflicts)
- [ ] Fix and update tests

2017-05-31 03:46 UTC, andrewda commented
I don't think we should close PR's that don't pass CI – or if we do make a very large timeout. Take this example: if the base `master` branch is failing for whatever reason, a PR to fix the CI would be _required_ to be merged before other PR's would start passing again (because we don't want to encourage people to fix CI issues in unrelated PR's).

2017-05-31 03:48 UTC, PlasmaPower commented
@andrewda I'd hope that this would prevent Travis from breaking on master, but you're right that it could still happen.

2017-05-31 03:51 UTC, andrewda commented
@PlasmaPower My main worry was that if something like fd6ce2758ffe792021ef2fdda26d424f06cde172 were to happen, where a hotfix is pushed without going through a PR.

2017-05-31 03:54 UTC, PlasmaPower commented
Oh yeah, good point.

2017-05-31 05:16 UTC, md678685 commented
In my opinion, if master is failing, we shouldn't force PRs to pass Travis, but if it is stable, we should add a timeout period to the end.

2017-05-31 07:25 UTC, phil-r commented
Nice ideas guys! I've updated TODO

2017-05-31 07:27 UTC, md678685 commented
Looks good now! 👍

2017-05-31 10:20 UTC, syvb approved these changes

2017-05-31 13:56 UTC, PlasmaPower commented
Ironic, this breaks Travis.

2017-05-31 13:57 UTC, PlasmaPower requested changes
I still don't see where it checks if master is failing.

2017-05-31 13:57 UTC, PlasmaPower commented on github_api/prs.py
> +        build_passed = has_build_passed(api, pr["statuses_url"])
You need to pass in the SHA here.

2017-05-31 14:14 UTC, phil-r commented on github_api/prs.py
> +        build_passed = has_build_passed(api, pr["statuses_url"])
yeah, didn't have time to finish, will try to do it this evening.

2017-05-31 20:57 UTC, PlasmaPower commented
Oh, sorry, I didn't see that this was WIP.

2017-06-01 02:35 UTC, phil-r commented
@PlasmaPower feel free to review, it's mostly finished, but I can't test as I have issues running docker after all updates.
Also I have no idea how I will resolve conflicts with #420 xD

2017-06-01 03:06 UTC, PlasmaPower requested changes

2017-06-01 03:06 UTC, PlasmaPower commented on github_api/prs.py
> +def close_stale_pr(api, urn, pr, delta, reason):
Maybe a better name like `handle_broken_pr`? This implies the PR is stale and it will close it.

2017-06-01 03:06 UTC, PlasmaPower commented
I checked, and Travis is run for new commits on master: https://github.com/chaosbot/Chaos/commits/master

Have you checked that this method of getting the status works?

2017-06-01 07:13 UTC, phil-r commented on github_api/prs.py
> +def close_stale_pr(api, urn, pr, delta, reason):
Thanks @PlasmaPower ! I've struggle so much with naming of this function ^_^

2017-06-01 22:02 UTC, phil-r commented
@PlasmaPower please review ;)

2017-06-01 22:04 UTC, PlasmaPower approved these changes

2017-06-01 22:08 UTC, andrewda approved these changes

2017-06-01 22:10 UTC, phil-r commented
Thanks, here is the spoils of ~war~ testing

2017-06-01 22:11 UTC, phil-r commented
🤦‍♂️ I've accidentally closed it

2017-06-02 01:10 UTC, merged

2017-06-02 21:00 UTC, while-loop commented
looks nice =D