For a true democracy all valid votes must be equal
Chaosthebot/Chaos pull request #42
Opened 2017-05-23 11:29 UTC by br0kend

In the interest of fairness and correctness, a truly democratic voting system should be used. No voter shall have more power than another one. The principles of equality should reflect the will of the people.

2017-05-23 11:31 UTC, 4a616d6573205265696c6c79 commented
👍

2017-05-23 11:35 UTC, leo-p commented
👍

2017-05-23 11:36 UTC, notjonmadden commented
👍

2017-05-23 11:40 UTC, jasondecastro commented
👍

2017-05-23 11:40 UTC, qn0x commented
:+1:

2017-05-23 11:51 UTC, PlasmaPower commented
`FOLLOWERS_LOG_BASE` should be removed from the config if this change goes through.

2017-05-23 11:53 UTC, GUIpsp commented
This shouldn't be merged because then anyone can make sockpuppets and manipulate the system.

2017-05-23 11:55 UTC, OpenNingia commented
@GUIpsp I don't follow; this PR only changes the weight of the votes, it doesn't remove them.

2017-05-23 12:02 UTC, pchauncey approved these changes

2017-05-23 12:04 UTC, qn0x commented
@OpenNingia I think what @GUIpsp meant is that everyone can create new accounts and thus make "their" option weigh more.

2017-05-23 12:05 UTC, OpenNingia commented
@qn0x They would have to wait a month tho, because that requisite was not lifted with this PR.

2017-05-23 12:12 UTC, jannemann commented
👍

2017-05-23 12:17 UTC, rec commented on github_api/voting.py
> +    weight = 1.0 if old_enough_to_vote else 0.0
Why not just `return float(age >= settings.MIN_VOTER_AGE)`?  Python guarantees that `True` and `False` always convert to `1.0` and `0.0`.

2017-05-23 12:18 UTC, MarHoff commented
👍

2017-05-23 12:22 UTC, netgusto commented on github_api/voting.py
> +    weight = 1.0 if old_enough_to_vote else 0.0
Because it keeps the intent clearer, while sticking to the original API (float) ?

2017-05-23 12:26 UTC, pchauncey requested changes
Please also update the README.md to reflect this change?

2017-05-23 12:34 UTC, copycat-killer commented
Your PR is too naive, this is not a perfect world.

You should implement something smart and hopefully not to big to prevent malicious people from doing as they please.

The log weighting is simple and it works, so I'm downvoting for now.

2017-05-23 12:35 UTC, rtzoeller commented
👍

2017-05-23 12:36 UTC, Nonepse commented
The debate here is to know what is better between a democracy and a meritocracy. I am in favor of meritocracy, so 👎

2017-05-23 12:37 UTC, dskoda1 commented
👍

2017-05-23 12:39 UTC, Fire-Hound commented
👎

2017-05-23 12:45 UTC, noway commented
Power to the people! 👍

2017-05-23 12:48 UTC, stoicio commented
:+1:

2017-05-23 12:48 UTC, copycat-killer commented
Did you read the PR? I believe this is not power to the people, which I'd want as well.

It's power to anything.

2017-05-23 12:49 UTC, Khoyo commented
This is *chaos*bot, so we should promote chaos. 👍

2017-05-23 12:49 UTC, svanschooten commented
While I do believe in the good of people and that they will not abuse a system like this, blockchain technology has been struggling with this problem for a while now. In that scope its called a [sybil attack](https://en.wikipedia.org/wiki/Sybil_attack) and there are methods to cope with this. The age method is quite simple and effective.

2017-05-23 12:51 UTC, maxcaron commented
👍

2017-05-23 13:01 UTC, jabbink commented
ITT: people without many followers.

2017-05-23 13:01 UTC, joelebeau1 commented
👍

2017-05-23 13:05 UTC, yozel commented on github_api/voting.py
> +    weight = 1.0 if old_enough_to_vote else 0.0
Explicit is better than implicit.

2017-05-23 13:11 UTC, MegaApuTurkUltra commented
👍

2017-05-23 13:13 UTC, b0o commented
Follower counts are just as easy to inflate as vote counts. Just have all of your fake accounts follow each other. 

Perhaps a better solution may be to hard-code usernames of trusted contributors who have some sort of regulated veto power but still otherwise have normal vote weight. 

This could help prevent blatantly malicious vote manipulation at the very least, while also maintaining a fairer voting system. Maybe these trusted users could also be able to blacklist known bot accounts.

2017-05-23 13:16 UTC, Raane commented
👍

2017-05-23 13:17 UTC, aloisdg commented
> For a true democracy all valid votes must be equal

I disagree. What about a Liquid/delegative democracy:


1. Choice of Role: Each member can choose to take either a passive role as an individual or an active role as a delegate, differentiating this from representative forms in which only specified representatives are allowed. Delegates have further choices as to how active they are and in what areas.
2. Low Barrier to Participation: The difficulty and cost of becoming a delegate is small, and in particular does not require political campaigning or winning a competitive election.
3. Delegated Authority: Delegates exercise power in organizational processes on behalf of themselves and those individuals who select them as their delegate. Different delegates, therefore, can exercise varying levels of decision power.
4. Privacy of the Individual: To avoid social pressures or coercion, all votes made by individuals are private, both from other individuals and from delegates.
5. Accountability of the delegates: To ensure the accountability of delegates to their voters and to the community at large, all formal deliberative decisions made by delegates are completely public (or in some forms viewable only to their constituents).
6. Specialization by Re-Delegation: Delegates can not only act directly on behalf of individuals as generalists, but through re-delegation they can also act on behalf of each other as specialists.

[More on Wikipedia](https://en.wikipedia.org/wiki/Delegative_democracy)!

2017-05-23 13:17 UTC, scf4 commented
Oh I love this idea. 

For extra chaos, is anyone interested in a PR which gives significantly more voting power to those who vote yes on the PR? :)

2017-05-23 13:19 UTC, MegaApuTurkUltra commented
> This could help prevent blatantly malicious vote manipulation at the very least, while also maintaining a fairer voting system. Maybe these trusted users could also be able to blacklist known bot accounts.

This is `chaos`bot. We don't care about preventing anything. The true will of the people must prevail.

2017-05-23 13:19 UTC, 4a616d6573205265696c6c79 commented
No gods, no masters.

I am dead against having certain users with more power than others. This isn't an oligarchy.

2017-05-23 13:22 UTC, b0o commented
> This is chaosbot. We don't care about preventing anything. The true will of the people must prevail.

The true will of the people, or of the one person with the biggest collection of fake github accounts? 😏

2017-05-23 13:23 UTC, uoaei commented
How about applying not a log function, but a sigmoid?

We can scale it by a certain constant (say, 5 or 10) to scale the effect of the number of followers.

e.g., using 2*Sigmoid(n/5). 

| Followers       | Votes assigned   |
|:-------------:|:-------------:|
| 0 | 1 |
| 5 | 1.46 |
| 10 | 1.76 |
| 20 | 1.96 |
| 30 | 2.00 |

The influence of "power users" quickly levels off.

Any fake accounts will need to gather followers to effectively take over the system, and it makes it harder for them to influence the system compared to when they already have the weight of real users. Maybe we can also include commits, watching, stars, etc. in the calculation, but this will complicate things considerably.

This adjustment would be like making something cost $2 vs it being free. You will discourage heavily the amount of dishonest behavior, despite the barrier not actually being that high.

2017-05-23 13:25 UTC, MegaApuTurkUltra commented
> The true will of the people, or of the one person with the biggest collection of fake github accounts? 

Check for accounts being X amount of time old and actively contributing on github? Using follower count is completely unnecessary.

2017-05-23 13:25 UTC, Ajedi32 requested changes
If this change goes through, the README needs to be updated: https://github.com/chaosbot/chaos#weights-and-thresholds

2017-05-23 13:48 UTC, averaart commented
👍

2017-05-23 14:05 UTC, libeclipse commented on github_api/voting.py
> +    weight = 1.0 if old_enough_to_vote else 0.0
I agree with @rec on this.

2017-05-23 14:06 UTC, libeclipse commented
*"All animals are equal, but some animals are more equal than others."*

👍

2017-05-23 14:07 UTC, perpetualjourney commented
Did you guys seriously not learn anything from Brexit? 👎

2017-05-23 14:08 UTC, awnumar approved these changes

2017-05-23 14:09 UTC, 0x62 approved these changes

2017-05-23 14:13 UTC, bperson commented
How about: every account starts the same voting power (regardless of any other metric). On each merged / rejected PR, whoever voted for the right outcome gets an increase in its voting power?

2017-05-23 14:15 UTC, drusepth commented
:+1:

2017-05-23 14:20 UTC, 4a616d6573205265696c6c79 commented
@bperson What is the *right* outcome? Why should people have more voting power because they happened to be on the winning side more often than not?

2017-05-23 14:21 UTC, libeclipse commented
@bperson nah, then when you have one feature merged, it's easier to get other features merged, and get more weight, and so on. It's an avalanche effect.

2017-05-23 14:29 UTC, merged

2017-05-23 14:45 UTC, bperson commented
@4a616d6573205265696c6c79 / @libeclipse  as you said, there is no "right" or "wrong" outcome :) The only thing you can do is limit or encourage certain behaviours.

All projects like this die out super quickly: encouraging activity and "giving a reward" for it is a behaviour worth encouraging imho and what we should optimise for.

@libeclipse you can limit the voting power (and even "decay" it) if needed. But in the beginning, an "avalanche effect" of activity is something worth encouraging imho, otherwise this leads nowhere :) 

In the meantime, this introduce a nice property / solve an issue that will arise if this project stays active: limiting the power of spammers. As demonstrated on this thread, all metrics that are outside this project's scope can be manipulated (follower count, activity on outside repos ... )

2017-05-23 14:49 UTC, rec commented on github_api/voting.py
> +    weight = 1.0 if old_enough_to_vote else 0.0
I'm always looking to reduce the number of conditionals, thus the cast, but I can see your point.

At the least, consider getting rid of the antipattern:

    weight = ...
    return weight

which has no documentary value here in a short function called `get_vote_weight`, leading to:

   return 1.0 if age >= settings.MIN_VOTER_AGE else 0.0

2017-05-23 17:38 UTC, Joshfindit commented
Avalanches are great...
unless you're in front of them.

2017-05-24 21:55 UTC, eukaryote31 commented on github_api/voting.py
> +    weight = 1.0 if old_enough_to_vote else 0.0
All votes are equal, but some are more equal than others.

2017-05-24 22:00 UTC, reddraggone9 commented on github_api/voting.py
> +    weight = 1.0 if old_enough_to_vote else 0.0
They're not real people if they're not old enough to vote.

2017-05-25 00:33 UTC, drusepth commented on github_api/voting.py
> +    weight = 1.0 if old_enough_to_vote else 0.0
Or have ideologies we disagree with.