[WIP] Fix PR push times
Chaosthebot/Chaos pull request #420
Opened 2017-05-31 01:06 UTC by mark-i-m

Currently if you push on a different branch on your fork, it will reset the time for all PRs from that fork, even if they are completely unrelated. This issue aims to fix that.

2017-05-31 02:32 UTC, PlasmaPower approved these changes

2017-05-31 02:35 UTC, andrewda approved these changes

2017-05-31 02:36 UTC, PlasmaPower commented
@mark-i-m Please fix the tests.

2017-05-31 02:40 UTC, mark-i-m commented
Working on it :)

2017-05-31 02:50 UTC, PlasmaPower commented
Still not fixed :(

If you could also expand the tests to with and without events present, that'd be great.

2017-05-31 02:51 UTC, PlasmaPower commented
and I'm assuming you know this, but you can run the tests locally of course.

2017-05-31 02:53 UTC, mark-i-m commented
Hmm... I am actually having trouble running them locally... which is why I am doing a lot of guessing...

2017-05-31 02:54 UTC, mark-i-m commented
What things do I need to pip install to run them locally?

2017-05-31 02:55 UTC, andrewda commented
Now it's just a linting issue 😝

2017-05-31 02:55 UTC, andrewda requested changes

2017-05-31 02:55 UTC, andrewda commented on tests/github_api/prs_test.py
> +            "ref" : "test_ref"
No space after `"ref"`

2017-05-31 02:56 UTC, mark-i-m commented
> If you could also expand the tests to with and without events present, that'd be great.

First, I need to figure out how the testing harness works... :stuck_out_tongue:

2017-05-31 03:02 UTC, PlasmaPower commented
@mark-i-m 

```
pip install -r requirements.txt
python -m unittest
```

`pip` might need root/admin, depending on your setup.

2017-05-31 03:17 UTC, PlasmaPower approved these changes
I would still appreciate tests for the event driven code, but I approve this PR as it stands

2017-05-31 03:21 UTC, mark-i-m commented
```$ python -m unittest github_api
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "github_api/__init__.py", line 7, in <module>
    import settings
  File "settings.py", line 2, in <module>
    import misc
  File "misc.py", line 2, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse```

2017-05-31 03:23 UTC, andrewda approved these changes
Also would like some tests if possible, but this looks good 👍

2017-05-31 03:25 UTC, PlasmaPower commented
@mark-i-m Python 3.6? If so, our `requirements.txt` might be off. I'll look into it.

2017-05-31 03:26 UTC, mark-i-m commented
Ah, that's true... ubuntu 16.04 only has python 3.5.2... Is there any way to run this in the docker container?

2017-05-31 03:27 UTC, PlasmaPower commented
@mark-i-m No idea, and that Python version might not even be a problem, IDK.

2017-05-31 03:30 UTC, andrewda commented
Tests pass, just linting now 👍

2017-05-31 03:32 UTC, andrewda requested changes

2017-05-31 03:32 UTC, andrewda commented on tests/github_api/prs_test.py
> +        self.assertEquals(last_updated, arrow.get("2017-01-01T00:00:10Z"))
`assertEquals` is deprecated in favor of `assertEqual` – small change but would get rid of the warning in the tests. Also on line 156

2017-05-31 03:41 UTC, PlasmaPower commented
Just a couple of indentation problems now, then it looks good to go!

2017-05-31 03:41 UTC, PlasmaPower commented
I'm assuming you have flake8 working locally?

2017-05-31 03:43 UTC, mark-i-m commented
TBH, I was playing around with the Dockerfile trying to run things in their... that seems like a much preferable option to installing things locally.

2017-05-31 03:43 UTC, PlasmaPower requested changes

2017-05-31 03:43 UTC, PlasmaPower commented on github_api/prs.py
> +    events = list(filter(lambda e: e["payload"]["ref"].split("/")[-1] == pr_ref, events))
Branch names can contain `/`s IIRC - try `'/'.join(arr[2:])` or similar.

2017-05-31 03:43 UTC, mark-i-m commented
Yay :tada: It works. Shall I unWIP?

2017-05-31 03:44 UTC, PlasmaPower commented
@mark-i-m almost, but I just noticed something. See above comment.

2017-05-31 03:44 UTC, PlasmaPower commented on github_api/prs.py
> +    events = list(filter(lambda e: e["type"] == "PushEvent", events))
Do you need to turn it into a list here? I think `filter` can take an iterator.

2017-05-31 03:46 UTC, PlasmaPower commented
One other thing I forgot: you should probably call `max(current_return_value, pr["created_at"])`.

2017-05-31 03:48 UTC, mark-i-m commented on github_api/prs.py
> +    events = list(filter(lambda e: e["type"] == "PushEvent", events))
Ah, yeah, I was printing the value so I need it as a list. Will fix

2017-05-31 03:49 UTC, mark-i-m commented
@PlasmaPower why?

2017-05-31 03:51 UTC, PlasmaPower commented
@mark-i-m A branch can be pushed for, then the PR for that created. We don't want an insta-close possible in that situation. It's happened before.

2017-05-31 03:52 UTC, mark-i-m commented
Hmm... that seems like it should be caller's problem, though?

2017-05-31 03:55 UTC, PlasmaPower commented
@mark-i-m sorta, but we should still handle it since it's easily possible.

2017-05-31 03:55 UTC, mark-i-m commented
The problem is that `max(current_return_value, pr["created_at"])` returns `current_return_value` always, right?

2017-05-31 03:56 UTC, PlasmaPower commented on github_api/prs.py
> +    ref_name = lambda e: '/'.join(e["payload"]["ref"].split("/")[3:]) == pr_ref
You sure about `[3:]`? wouldn't `my_branch_name` be index 2?

2017-05-31 03:58 UTC, PlasmaPower commented
@mark-i-m not always - reread my example:

1. Author pushes to `example-branch`
2. Author waits a couple hours
3. Author makes a PR for `example-branch`
4. Author's PR gets instantly closed
    - Current return value: time of 1 (too soon)
    - `pr["created_at"]`: time of 3 (correct)

This can also happen when a PR is recreated to address conflicts/other issues. It's happened before.

2017-05-31 03:58 UTC, mark-i-m commented on github_api/prs.py
> +    ref_name = lambda e: '/'.join(e["payload"]["ref"].split("/")[3:]) == pr_ref
"/ref/head/blah" => ["", "ref", "head", "blah"]

2017-05-31 04:02 UTC, mark-i-m commented
Oh, I thought by `current_return_value` you meant the value without this PR... I see now that I misread your post. Yes, that makes sense.

2017-05-31 04:04 UTC, PlasmaPower commented
Oh I could see how that would be confusing. Great work on this! It's a shame it's slowing down your other PRs haha.

2017-05-31 04:04 UTC, mark-i-m commented
Lol, the irony :laughing:

2017-05-31 04:30 UTC, mark-i-m commented
Sorry, everyone... I need to sleep... will finish this up tomorrow :zzz:

2017-05-31 04:30 UTC, PlasmaPower commented
Sounds good! Can't wait.

2017-05-31 04:50 UTC, PlasmaPower commented on github_api/prs.py
> +            return arrow.get(repo["pushed_at"])
I think we want to max this with `pr_data["created_at"]` too.

2017-05-31 04:54 UTC, PlasmaPower commented
> I need to sleep... will finish this up tomorrow

Sleep... nah

2017-05-31 05:48 UTC, md678685 commented
/essay
😛

2017-05-31 05:55 UTC, andrewda commented
wow @anythingbot good read 👍

2017-05-31 05:56 UTC, md678685 commented
~~Meanwhile, in the UK...~~

2017-05-31 23:47 UTC, mark-i-m commented on github_api/prs.py
> +            return arrow.get(repo["pushed_at"])
Hmmm... then how did it work before?

2017-05-31 23:47 UTC, mark-i-m commented on github_api/prs.py
> +            return arrow.get(repo["pushed_at"])
I mean, it makes sense

2017-05-31 23:50 UTC, PlasmaPower commented on github_api/prs.py
> +            return arrow.get(repo["pushed_at"])
It didn't work. A number of PRs got insta-closed and one got insta-merged before the threshold increase.

2017-06-01 00:57 UTC, mark-i-m commented
Can anyone decipher the error on that last failing test?

2017-06-01 01:09 UTC, mark-i-m commented
Nvm... got it :tada:

2017-06-01 01:10 UTC, PlasmaPower commented
@mark-i-m I realized the patches were getting mixed up - never would have guess it needs to be in reversed.

2017-06-01 01:11 UTC, mark-i-m commented
Yeah, that's pretty unintuitive

2017-06-01 01:11 UTC, PlasmaPower commented
Looks like that arg line is a bit too long.

2017-06-01 01:14 UTC, PlasmaPower commented
@mark-i-m Wrong line - it's the arg line of the test we were working on.

2017-06-01 01:20 UTC, PlasmaPower approved these changes
Looks good! :tada:

2017-06-01 01:21 UTC, PlasmaPower commented on github_api/prs.py
> +    ref_name = lambda e: '/'.join(e["payload"]["ref"].split("/")[3:]) == pr_ref
Oh, that makes a lot of sense. Thanks!

2017-06-01 04:47 UTC, merged