[WIP] Add a Twitter Api according to #364
Chaosthebot/Chaos pull request #443
Opened 2017-06-01 02:10 UTC by eamanu

The `twitter_api.Twitter.PostTwitter(message)` receive a message and make a Tweet
Is necessary have a `twitter_api.secre`t like `github_pat.secret` with the next format
```
consumer_key='1234...'
consumer_secret='1234...'
access_token='12345...'
access_secret='1234...'
```

Todo List:
1. Test twitter_api
1. create a Twitter Apps (https://apps.twitter.com/) for ChaosBot and complete the twitter_api.secret

2017-06-01 02:16 UTC, rudehn commented
I would recommend putting your twitter keys into a json file. Then loading them is as simple as `keys = json.load(file_pointer)`

2017-06-01 02:22 UTC, phil-r commented
To add token/secret we can use `encryption` module added in #227

2017-06-01 20:44 UTC, hongaar commented
@phil-r would be nice if we could add this to the wiki!

2017-06-01 22:54 UTC, phil-r commented
@hongaar added: https://github.com/chaosbot/Chaos/wiki/Encryption

2017-06-02 19:13 UTC, syvb approved these changes

2017-06-06 10:01 UTC, bobjoe27326 commented
:+1:

2017-06-06 20:58 UTC, eamanu commented
@phil-r I don't undestand how can I use the encryptation with the Twitter's keys. Can you make a little sample?

2017-06-07 11:20 UTC, syvb approved these changes

2017-06-07 14:38 UTC, Swizz commented
Is Chaosbot :-1: referenced as a negative vote ? Oo

2017-06-07 16:21 UTC, andrewda requested changes
Maybe a tweet when a PR gets merged, or created. Maybe also change the current tweets to "Starting up..." instead of two simultaneous tweets when starting up.

2017-06-07 16:21 UTC, andrewda commented on chaos.py
> +    ta.Twitter.PostTwitter("checking if I crashed before...", api_twitter.GetApi())
Do we really want it to be this verbose? I don't think it needs to tweet this out every time it starts up.

2017-06-07 16:21 UTC, andrewda commented on chaos.py
> +    ta.Twitter.PostTwitter("starting up and entering event loop", api_twitter.GetApi())
Same as above.

2017-06-07 17:17 UTC, rudehn commented
I think anything posted to twitter should be important. The info posted right now is better suited to log files

2017-06-07 18:18 UTC, eamanu commented
@rudehn @andrewda I will make that Chaosbot make tweets when there are  PR or Merges. What are the files that make the PR or files of interest to change?

2017-06-07 18:31 UTC, eamanu commented on chaos.py
> +    ta.Twitter.PostTwitter("checking if I crashed before...", api_twitter.GetApi())
I think like @rudehn. Anything posted to twitter should be important. A post in twitter isn't a cost or some extra.

2017-06-07 18:31 UTC, eamanu commented on chaos.py
> +    ta.Twitter.PostTwitter("starting up and entering event loop", api_twitter.GetApi())
Same as above :+1:

2017-06-07 18:41 UTC, PlasmaPower commented
@eamanu It probably should tweet when any PR gets merged. Alternatively, we could ignore PRs with only documentation changes (no `*.py` files touched).

2017-06-07 18:42 UTC, closed without merging

2017-06-07 18:43 UTC, eamanu reviewed
I think like @rudehn. Anything posted to twitter should be important. A post in twitter isn't a cost or some extra

2017-06-08 01:22 UTC, mark-i-m commented
I suspect that posting crashes might be good...

2017-06-08 18:54 UTC, dbpokorny commented
> I suspect that posting crashes might be good...

https://www.youtube.com/watch?v=bQlpDiXPZHQ

Life Call Commercial "I've fallen and I can't get up!"

> I'm having interpreter pain!

> I've halted, and I can't restart!