[WIP] Switch to a hug-based API
Chaosthebot/Chaos pull request #488
Opened 2017-06-02 20:14 UTC by md678685

This will make life much easier when we move from dumping JSON files in the server root to using a database (MySQL/SQLite).

I'm not sure what changes will need to be made on the real ChaosBot server to get Nginx to forward uWSGI properly, but I've modified the Docker `start_services.sh` script to link the new config properly.

(Note: 69d7aff says "incomplete" because currently, `/` serves the hug help API and you need to visit `/index.html` to show the index.)

2017-06-02 20:22 UTC, rudehn commented on webserver.py
> +            meritocracy = meritocracy[:amount]
is meritocracy defined here?

2017-06-02 20:22 UTC, rudehn commented on webserver.py
> +            voters = voters[:amount]
is voters defined here?

2017-06-02 20:24 UTC, md678685 commented on webserver.py
> +            voters = voters[:amount]
Yes, it is. If the sorted call returns null for some reason, it will be caught.

2017-06-02 20:24 UTC, md678685 commented on webserver.py
> +            meritocracy = meritocracy[:amount]
Same as before

2017-06-02 20:26 UTC, rudehn commented on webserver.py
> +            voters = voters[:amount]
I mean is voters initially scope limited to the `with` block?

2017-06-02 20:45 UTC, hongaar commented
Have no experience with hug or uwsgi but looks incredible, so :+1:

2017-06-02 21:16 UTC, md678685 commented on webserver.py
> +            voters = voters[:amount]
I've tested it and that doesn't appear to be the case.

2017-06-02 21:17 UTC, md678685 commented
@hongaar I don't have much experience with them either 😛

2017-06-02 21:18 UTC, PlasmaPower commented on webserver.py
> +            voters = voters[:amount]
@rudehn python scopes are classes and functions only.

2017-06-02 21:19 UTC, PlasmaPower commented on webserver.py
> +        with open("/root/workspace/Chaos/server/voters.json", "r") as f:
Cache this?

2017-06-02 21:20 UTC, PlasmaPower commented on webserver.py
> +def get_meritocracy(amount: hug.types.number = 20):
Do we really need a maximum amount for this?

2017-06-02 21:38 UTC, Swizz commented
@hongaar If you take a look at the gitter chat, we choose hug and moon for the web api/site for ease.
We heavily decided to choose simplicity and minimalism first.

@md678685 Do you need me on some stuff ?

2017-06-02 21:41 UTC, md678685 commented
@Swizz If you want to add anything else (or you're particularly experienced with Nginx 😉) then that'd be great!

2017-06-02 21:45 UTC, Swizz commented
Front end dev, know nothing about Nginx

2017-06-02 21:46 UTC, md678685 commented
Fair enough, I'll try and sort the index issue out

2017-06-03 08:41 UTC, md678685 commented
I think this is ready for merging - could we get a meritocracy review? @PlasmaPower

2017-06-03 16:08 UTC, PlasmaPower requested changes
This will currently break the top voters card, as you're requesting the first 20 voters, not the top 20 voters.

2017-06-03 17:01 UTC, md678685 commented
@PlasmaPower The voters are now sorted in descending (highest to lowest) order before it gets limited by the amount.

2017-06-03 20:16 UTC, PlasmaPower approved these changes

2017-06-03 20:16 UTC, merged