Add a label to PR regarding changes
Chaosthebot/Chaos pull request #502
Opened 2017-06-03 21:25 UTC by Swizz

Files and directories are under "part name".
The cron task will read the patch file from the PR and apply a label regarding changes.

![label on PR](http://i.imgur.com/1FXR3PM.png)

2017-06-03 21:31 UTC, PlasmaPower commented on settings.py
> +    "core": ["cron/*", "chaos.py"],
Maybe separate out files in `cron`, as they handle very different parts of chaos.

2017-06-03 21:31 UTC, Swizz commented
I love the way Chaos judge me with label, and remove it after change. Lets add more labels !

2017-06-03 21:33 UTC, Swizz commented on settings.py
> +    "core": ["cron/*", "chaos.py"],
Everything is possible. I use `fnmatch`
I worked on feature, that why this is in settings o/

Suggest me change you want :)

2017-06-03 21:42 UTC, PlasmaPower commented on settings.py
> +    "core": ["cron/*", "chaos.py"],
```
"issues": ["cron/*issue*.py"],
"pull_requests": ["cron/poll_pull_requests.py"],
"core": ["cron/*", "chaos.py"],
```

2017-06-03 21:45 UTC, PlasmaPower requested changes

2017-06-03 21:45 UTC, PlasmaPower commented on settings.py
> +SOURCE_PARTS_NAME = {
Should be an `OrderedDict`. Otherwise, some generalizations could end up before the specifics (e.g. what is `misc` ends up first?).

2017-06-03 21:47 UTC, Swizz commented on settings.py
> +SOURCE_PARTS_NAME = {
I am not a Python expert :/

OrderedDict ensure iteration to follow the initial given order ?
Dict iteration is unpredictable ?

2017-06-03 21:52 UTC, PlasmaPower commented on settings.py
> +SOURCE_PARTS_NAME = {
Exactly

2017-06-03 22:06 UTC, Swizz commented
Here we go

2017-06-03 22:15 UTC, PlasmaPower commented
> Update settings for meritocracy pleasure

:disappointed:

2017-06-03 22:16 UTC, PlasmaPower approved these changes

2017-06-03 22:23 UTC, PlasmaPower commented on cron/poll_pull_requests.py
> +            patched_files = gh.prs.get_patch(api, settings.URN, pr_num)
You might want to try-catch this (and the following labeling code) just in case.

2017-06-04 00:50 UTC, MUCHZER commented
Or extend meritocracy ?

2017-06-04 00:51 UTC, andrewda commented
@anythingbot There are pending reviews that still need to be addressed. @PlasmaPower suggested adding a try/catch block to prevent even more ChaosBot crashes, and there's a typo to fix that you reviewed.

2017-06-04 00:51 UTC, PlasmaPower commented
I'd prefer error handling before a positive review, but I guess I'll approve it anyway.

2017-06-04 00:52 UTC, andrewda commented
@PlasmaPower I think error handling is pretty important, and should probably be added first.

2017-06-04 00:52 UTC, PlasmaPower commented
Okay. I'll create an issue to get people's opinions on if we should approve in these cases.

2017-06-04 04:12 UTC, closed without merging

2017-06-04 06:10 UTC, andrewda commented
@Swizz resubmit with the above fixes ❤️

2017-06-04 08:17 UTC, Swizz commented
It was around 3 AM in my timezone when you writed this.
Meritocratic are rude !

I will work on it.

2017-06-04 08:57 UTC, hongaar commented
Really nice feature!

2017-06-06 14:56 UTC, Swizz commented
Reopening this PR works or do I need to open a fresh new one ?