PR Owners can change their minds
Chaosthebot/Chaos pull request #77
Opened 2017-05-23 17:27 UTC by JordanReiter

If a PR owner changes their mind & votes against the pull request, that vote should count.
Also I went ahead and switched to a gender-neutral pronoun.

2017-05-23 17:44 UTC, pchauncey requested changes
Please also update the README.md to reflect this change?

2017-05-23 18:04 UTC, YBadiss commented on github_api/voting.py
> +    if votes.get('pr_owner') != -1:
this is incorrect, should be `votes.get(pr_owner)`

2017-05-23 18:07 UTC, Ajedi32 commented on github_api/voting.py
> +    if votes.get('pr_owner') != -1:
Thanks, I was just about to point that out. 

This line in its current form actually just allows the GitHub user named "pr_owner" to override the actual PR owner's vote. Also, I feel it's worth pointing out that as of the moment of this review, there are 23 other people who voted for this PR without noticing this mistake.

2017-05-23 18:08 UTC, Ajedi32 commented
Can't the PR owner already just veto the PR if they choose by closing it themselves?

2017-05-23 18:10 UTC, JordanReiter commented
@Ajedi32 probably but they may as well still have the option. Maybe they end up with misgivings about the pull request but still want it to be decided by a vote.

2017-05-23 18:18 UTC, pchauncey approved these changes

2017-05-23 18:18 UTC, JordanReiter commented on github_api/voting.py
> +    if votes.get('pr_owner') != -1:
OMG This thing needs to have tests… that's going to be interesting.

2017-05-23 19:11 UTC, patricknelson commented
Related: #82 PR owners can submit code that was not what was voted for and use it as a method to inject unexpected malicious code.

2017-05-23 19:19 UTC, rudehn commented
Related #48 somehow got through.

2017-05-23 22:17 UTC, viktorsec commented
@JordanReiter please resolve conflicts

2017-05-26 01:03 UTC, closed without merging

2017-05-26 01:59 UTC, patricknelson commented
Oh... oh my god... it's conscious and has an attitude. WE'RE DOOMED :robot: